// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuthResponse struct {
	Token  string `json:"token"`
	UserId string `json:"userId"`
}

type ChatRequest struct {
	UserId  string `json:"userId"`
	Message string `json:"message"`
	RoomId  string `json:"roomId,optional"`
}

type CreateRoomRequest struct {
	OwnerId    string `json:"ownerId"`
	MaxMembers int    `json:"maxMembers"`
}

type Diary struct {
	DiaryId    string `json:"diaryId"`
	UserId     string `json:"userId"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Visibility bool   `json:"visibility"`
	EntryDate  string `json:"entryDate"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type DiaryListRequest struct {
	UserId   string `form:"userId"`
	PageNum  int    `form:"pageNum,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	SortBy   string `form:"sortBy,optional"`
	Asc      bool   `form:"asc,default=true"`
}

type DiaryListResponse struct {
	Total   int64   `json:"total"`
	List    []Diary `json:"list"`
	Page    int     `json:"page"`
	PerPage int     `json:"perPage"`
}

type EditDiaryRequest struct {
	DiaryId    string `json:"diaryId"`
	Title      string `json:"title,optional"`
	Content    string `json:"content,optional"`
	Visibility bool   `json:"visibility,optional"`
}

type JoinRoomRequest struct {
	Code   string `json:"code"`
	UserId string `json:"userId"`
}

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type RegisterRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SituationReport struct {
	Code       string                 `json:"code"`
	Summary    string                 `json:"summary"`
	Narratives map[string]interface{} `json:"narratives"`
}

type SituationRoom struct {
	Code       string   `json:"code"`
	OwnerId    string   `json:"ownerId"`
	MaxMembers int      `json:"maxMembers"`
	Members    []string `json:"members"`
	Status     string   `json:"status"`
	ScenarioId string   `json:"scenarioId,optional"`
}

type StartRoomRequest struct {
	Code       string `json:"code"`
	ScenarioId string `json:"scenarioId"`
	OwnerId    string `json:"ownerId"`
}

type SubmitNarrativeRequest struct {
	Code      string `json:"code"`
	UserId    string `json:"userId"`
	Narrative string `json:"narrative"`
}

type User struct {
	UserId   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
}

type WriteDiaryRequest struct {
	UserId     string `json:"userId"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Visibility bool   `json:"visibility"`
	EntryDate  string `json:"entryDate"`
}
