// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ai "yusi-backend/internal/handler/ai"
	diary "yusi-backend/internal/handler/diary"
	room "yusi-backend/internal/handler/room"
	user "yusi-backend/internal/handler/user"
	"yusi-backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// AI 聊天（流式）
					Method:  http.MethodPost,
					Path:    "/chat/stream",
					Handler: ai.ChatStreamHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 写日记
					Method:  http.MethodPost,
					Path:    "/",
					Handler: diary.WriteDiaryHandler(serverCtx),
				},
				{
					// 编辑日记
					Method:  http.MethodPut,
					Path:    "/",
					Handler: diary.EditDiaryHandler(serverCtx),
				},
				{
					// 获取日记详情
					Method:  http.MethodGet,
					Path:    "/:diaryId",
					Handler: diary.GetDiaryHandler(serverCtx),
				},
				{
					// 删除日记
					Method:  http.MethodDelete,
					Path:    "/:diaryId",
					Handler: diary.DeleteDiaryHandler(serverCtx),
				},
				{
					// 获取日记列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: diary.GetDiaryListHandler(serverCtx),
				},
				{
					// 搜索日记
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: diary.SearchDiaryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/diary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建房间
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: room.CreateRoomHandler(serverCtx),
				},
				{
					// 加入房间
					Method:  http.MethodPost,
					Path:    "/join",
					Handler: room.JoinRoomHandler(serverCtx),
				},
				{
					// 获取报告
					Method:  http.MethodGet,
					Path:    "/report/:code",
					Handler: room.GetReportHandler(serverCtx),
				},
				{
					// 开始房间
					Method:  http.MethodPost,
					Path:    "/start",
					Handler: room.StartRoomHandler(serverCtx),
				},
				{
					// 提交叙述
					Method:  http.MethodPost,
					Path:    "/submit",
					Handler: room.SubmitNarrativeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/room"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 用户登出
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)
}
